### ISSUE TITLE
Installing Home Assistant on Muse Luxe not possible

### ISSUE THREAD

**Issue by gatonero** [RASPIAUDIO/esphomeLuxe#5]
Installing Home Assistant on a Raspiaudio Muse Lux results in the error "

> E (1734) spi_flash: Detected size(4096k) smaller than the size in the binary image header(8192k). Probe failed.

" The device reboots and produces the same error over and over again.

[esp-web-tools-logs.txt](https://github.com/user-attachments/files/19601142/esp-web-tools-logs.txt)

**Comment by gatonero** [comment]
https://aachen-kostroma.de/event/april-stammtisch-aachen-kostroma/

Am Fr., 4. Apr. 2025 um 10:57 Uhr schrieb gatonero ***@***.***

**Comment by albanleandri** [comment]
I experienced the same issues. I tried to reinstall both my Muse Luxe, cause they had the same issue: The last message broadcasted is announced again and again, as if it was never removed from a queue, somehow...
And, when reinstalling Muse Luxe for Home Assistant from this website [https://raspiaudio.github.io/](https://raspiaudio.github.io/), I had the same issue as above... I am pasting exactly what have in the logs. Please help

```
Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7112
load:0x40078000,len:15624
load:0x40080400,len:4
load:0x40080404,len:3876
entry 0x4008064c
I (29) boot: ESP-IDF 5.1.5 2nd stage bootloader
I (29) boot: compile time Apr  2 2025 12:29:42
I (29) boot: Multicore bootloader
I (33) boot: chip revision: v1.0
I (37) boot.esp32: SPI Speed      : 40MHz
I (42) boot.esp32: SPI Mode       : DIO
I (46) boot.esp32: SPI Flash Size : 8MB
I (51) boot: Enabling RNG early entropy source...
I (56) boot: Partition Table:
I (60) boot: ## Label            Usage          Type ST Offset   Length
I (67) boot:  0 otadata          OTA data         01 00 00009000 00002000
I (75) boot:  1 phy_init         RF data          01 01 0000b000 00001000
I (82) boot:  2 app0             OTA app          00 10 00010000 001c0000
I (89) boot:  3 app1             OTA app          00 11 001d0000 001c0000
I (97) boot:  4 nvs              WiFi data        01 02 00390000 0006d000
I (104) boot: End of partition table
I (109) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=5fb34h (391988) map
I (259) esp_image: segment 1: paddr=0006fb5c vaddr=3ffb0000 size=004bch (  1212) load
I (260) esp_image: segment 2: paddr=00070020 vaddr=400d0020 size=ffa00h (1047040) map
I (643) esp_image: segment 3: paddr=0016fa28 vaddr=3ffb04bc size=03778h ( 14200) load
I (648) esp_image: segment 4: paddr=001731a8 vaddr=40080000 size=19ce4h (105700) load
I (705) boot: Loaded app from partition at offset 0x10000
I (705) boot: Disabling RNG early entropy source...
I (717) cpu_start: Multicore app
I (718) quad_psram: This chip is ESP32-D0WD
I (718) esp_psram: Found 8MB PSRAM device
I (719) esp_psram: Speed: 40MHz
I (723) esp_psram: PSRAM initialized, cache is in low/high (2-core) mode.
W (731) esp_psram: Virtual address not enough for PSRAM, map as much as we can. 4MB is mapped
I (740) cpu_start: Pro cpu up.
I (743) cpu_start: Starting app cpu, entry point is 0x40082a68
I (736) cpu_start: App cpu up.
I (1626) esp_psram: SPI SRAM memory test OK
I (1634) cpu_start: Pro cpu start user code
I (1634) cpu_start: cpu freq: 160000000 Hz
I (1634) cpu_start: Application information:
I (1637) cpu_start: Project name:     muse-luxe
I (1642) cpu_start: App version:      2025.3.2
I (1648) cpu_start: Compile time:     Apr  2 2025 12:28:57
I (1654) cpu_start: ELF file SHA256:  4fcc4d6788995f1a...
I (1660) cpu_start: ESP-IDF:          5.1.5
I (1665) cpu_start: Min chip rev:     v0.0
I (1669) cpu_start: Max chip rev:     v3.99 
I (1674) cpu_start: Chip rev:         v1.0
I (1680) heap_init: Initializing. RAM available for dynamic allocation:
I (1687) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (1693) heap_init: At 3FFB8D00 len 00027300 (156 KiB): DRAM
I (1699) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (1705) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (1712) heap_init: At 40099CE4 len 0000631C (24 KiB): IRAM
I (1719) esp_psram: Adding pool of 4096K of PSRAM memory to heap allocator
I (1727) spi_flash: detected chip: generic
I (1731) spi_flash: flash io: dio
E (1735) spi_flash: Detected size(4096k) smaller than the size in the binary image header(8192k). Probe failed.

assert failed: do_core_init startup.c:350 (flash_ret == ESP_OK)


Backtrace: 0x4008375d:0x3ffe3ab0 0x4008d6f9:0x3ffe3ad0 0x40093e0d:0x3ffe3af0 0x4013ccc2:0x3ffe3c10 0x40082e4d:0x3ffe3c50 0x400796d5:0x3ffe3c80 |<-CORRUPTED




ELF file SHA256: 4fcc4d6788995f1a

Rebooting...
```

**Comment by gatonero** [comment]
My issue is solved right know.  The installation was a bit complicated but it worked at last. See https://forum.raspiaudio.com/t/problem-flashing-muse-luxe-v2/1265/10

**Comment by albanleandri** [comment]
Hello @RASPIAUDIOadmin , I still have the same issue

I connect via my PC and USB cable to the Muse Luxe
Chrome ==> [raspiaudio.github.io 1](http://raspiaudio.github.io/)
follow instructions…
Then after "Wrapping up"  -> It's it worked -< Next... but no Wifi configuration form
and still the same problem in the logs
Pasting below in case you see something:
```
E (1759) spi_flash: Detected size(4096k) smaller than the size in the binary image header(8192k). Probe failed.

assert failed: do_core_init startup.c:350 (flash_ret == ESP_OK)


Backtrace: 0x40084691:0x3ffe3ab0 0x4008d6f9:0x3ffe3ad0 0x40093e0d:0x3ffe3af0 0x4013c3be:0x3ffe3c10 0x40083d81:0x3ffe3c50 0x400796d5:0x3ffe3c80 |<-CORRUPTED




ELF file SHA256: 67b56daa55c90dd8

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7112
load:0x40078000,len:15624
load:0x40080400,len:4
load:0x40080404,len:3876
entry 0x4008064c
I (29) boot: ESP-IDF 5.1.5 2nd stage bootloader
I (29) boot: compile time Apr 29 2025 12:12:36
I (29) boot: Multicore bootloader
I (33) boot: chip revision: v1.0
I (37) boot.esp32: SPI Speed      : 40MHz
I (42) boot.esp32: SPI Mode       : DIO
I (46) boot.esp32: SPI Flash Size : 8MB
I (51) boot: Enabling RNG early entropy source...
I (56) boot: Partition Table:
I (60) boot: ## Label            Usage          Type ST Offset   Length
I (67) boot:  0 otadata          OTA data         01 00 00009000 00002000
I (75) boot:  1 phy_init         RF data          01 01 0000b000 00001000
I (82) boot:  2 app0             OTA app          00 10 00010000 001c0000
I (89) boot:  3 app1             OTA app          00 11 001d0000 001c0000
I (97) boot:  4 nvs              WiFi data        01 02 00390000 0006d000
I (104) boot: End of partition table
I (109) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=74a0ch (477708) map
I (290) esp_image: segment 1: paddr=00084a34 vaddr=3ffb0000 size=03c14h ( 15380) load
I (296) esp_image: segment 2: paddr=00088650 vaddr=40080000 size=079c8h ( 31176) load
I (309) esp_image: segment 3: paddr=00090020 vaddr=400d0020 size=fe624h (1041956) map
I (686) esp_image: segment 4: paddr=0018e64c vaddr=400879c8 size=1231ch ( 74524) load
I (730) boot: Loaded app from partition at offset 0x10000
I (730) boot: Disabling RNG early entropy source...
I (741) cpu_start: Multicore app
I (742) quad_psram: This chip is ESP32-D0WD
I (743) esp_psram: Found 8MB PSRAM device
I (743) esp_psram: Speed: 40MHz
I (747) esp_psram: PSRAM initialized, cache is in low/high (2-core) mode.
W (755) esp_psram: Virtual address not enough for PSRAM, map as much as we can. 4MB is mapped
I (764) cpu_start: Pro cpu up.
I (768) cpu_start: Starting app cpu, entry point is 0x4008399c
I (760) cpu_start: App cpu up.
I (1650) esp_psram: SPI SRAM memory test OK
I (1658) cpu_start: Pro cpu start user code
I (1658) cpu_start: cpu freq: 160000000 Hz
I (1658) cpu_start: Application information:
I (1662) cpu_start: Project name:     muse-luxe
I (1667) cpu_start: App version:      2025.4.0
I (1672) cpu_start: Compile time:     Apr 29 2025 12:11:56
I (1678) cpu_start: ELF file SHA256:  67b56daa55c90dd8...
I (1684) cpu_start: ESP-IDF:          5.1.5
I (1689) cpu_start: Min chip rev:     v0.0
I (1694) cpu_start: Max chip rev:     v3.99 
I (1699) cpu_start: Chip rev:         v1.0
I (1704) heap_init: Initializing. RAM available for dynamic allocation:
I (1711) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (1717) heap_init: At 3FFB8CD8 len 00027328 (156 KiB): DRAM
I (1723) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (1730) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (1736) heap_init: At 40099CE4 len 0000631C (24 KiB): IRAM
I (1743) esp_psram: Adding pool of 4096K of PSRAM memory to heap allocator
I (1751) spi_flash: detected chip: generic
I (1755) spi_flash: flash io: dio
E (1759) spi_flash: Detected size(4096k) smaller than the size in the binary image header(8192k). Probe failed.

assert failed: do_core_init startup.c:350 (flash_ret == ESP_OK)


Backtrace: 0x40084691:0x3ffe3ab0 0x4008d6f9:0x3ffe3ad0 0x40093e0d:0x3ffe3af0 0x4013c3be:0x3ffe3c10 0x40083d81:0x3ffe3c50 0x400796d5:0x3ffe3c80 |<-CORRUPTED




ELF file SHA256: 67b56daa55c90dd8

Rebooting...
```

**Comment by gatonero** [comment]
Try resetting the Muse Luxe while installing the firmware. To do this, press the hidden button in the AUX port with a paperclip and then press "Install".

**Comment by rgnet5** [comment]
@gatonero   I don't see an actual solution here.  You reference a new bin file, but where do we get it and how do we install it? 
https://raspiaudio.github.io/ still has the version that causes the problem.
 
https://github.com/RASPIAUDIO/esphomeLuxe/issues/5#issuecomment-2838494116
