### ISSUE TITLE
HomeAssistant Installation from raspiaudio.com not possible & custom luxe_microWW.yaml fails install

### ISSUE THREAD

**Issue by mdoliver** [RASPIAUDIO/esphomeLuxe#6]
Using ESPHome 2025.3.3

When I try installing Luxe/Home Assistant from https://apps.raspiaudio.com I get the same issue as [@gatonero ](https://github.com/RASPIAUDIO/esphomeLuxe/issues/5)

When I try the yaml code from luxe_microWW.yaml I get a failed installation with the following output:

`Compiling .pioenvs/muse-luxe/src/esphome/components/micro_wake_word/micro_wake_word.cpp.o
Compiling .pioenvs/muse-luxe/src/esphome/components/micro_wake_word/streaming_model.cpp.o
In file included from src/esphome/components/micro_wake_word/micro_wake_word.h:6,
                 from src/esphome/components/micro_wake_word/micro_wake_word.cpp:1:
src/esphome/components/micro_wake_word/streaming_model.h:7:10: fatal error: tensorflow/lite/core/c/common.h: No such file or directory
    7 | #include <tensorflow/lite/core/c/common.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/muse-luxe/src/esphome/components/micro_wake_word/micro_wake_word.cpp.o] Error 1
In file included from src/esphome/components/micro_wake_word/streaming_model.cpp:3:
src/esphome/components/micro_wake_word/streaming_model.h:7:10: fatal error: tensorflow/lite/core/c/common.h: No such file or directory
    7 | #include <tensorflow/lite/core/c/common.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/muse-luxe/src/esphome/components/micro_wake_word/streaming_model.cpp.o] Error 1
========================== [FAILED] Took 5.87 seconds ==========================`

**Comment by albanleandri** [comment]
Hi still no news here? I can use my two Muse Luxe since this issue. I also posted in the other discussion from @gatonero

**Comment by gatonero** [comment]
Since weeks weeks my raspiaudi muse is bricked. See [Installing Home Assistant on Muse Luxe not possible](https://github.com/RASPIAUDIO/esphomeLuxe/issues/5#issuecomment-2802556559)

**Comment by RASPIAUDIOadmin** [comment]
Solved in last version on apps.raspiaudio.com

**Comment by albanleandri** [comment]
Sorry, for me, this issue isn't closed. The new software doesn't fix one of my Muse Luxe, plus the "reset"  button within the AUX port doesn't seem to do any resetting at all. I still can't initialize my WiFi credentials.

Still this error...

```
Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x33 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7176
load:0x40078000,len:15564
ho 0 tail 12 room 4
load:0x40080400,len:4
load:0x40080404,len:3904
entry 0x40080638
I (31) boot: ESP-IDF 5.3.2 2nd stage bootloader
I (31) boot: compile time Jul  3 2025 11:20:48
I (31) boot: Multicore bootloader
I (35) boot: chip revision: v1.0
I (39) boot.esp32: SPI Speed      : 40MHz
I (44) boot.esp32: SPI Mode       : DIO
I (48) boot.esp32: SPI Flash Size : 8MB
I (53) boot: Enabling RNG early entropy source...
I (58) boot: Partition Table:
I (62) boot: ## Label            Usage          Type ST Offset   Length
I (69) boot:  0 otadata          OTA data         01 00 00009000 00002000
I (76) boot:  1 phy_init         RF data          01 01 0000b000 00001000
I (84) boot:  2 app0             OTA app          00 10 00010000 001c0000
I (91) boot:  3 app1             OTA app          00 11 001d0000 001c0000
I (99) boot:  4 nvs              WiFi data        01 02 00390000 0006d000
I (106) boot: End of partition table
I (111) esp_image: segment 0: paddr=00010020 vaddr=3f400020 size=6d408h (447496) map
I (272) esp_image: segment 1: paddr=0007d430 vaddr=3ffb0000 size=02be8h ( 11240) load
I (277) esp_image: segment 2: paddr=00080020 vaddr=400d0020 size=fd7c4h (1038276) map
I (634) esp_image: segment 3: paddr=0017d7ec vaddr=3ffb2be8 size=01650h (  5712) load
I (636) esp_image: segment 4: paddr=0017ee44 vaddr=40080000 size=1b10ch (110860) load
I (697) boot: Loaded app from partition at offset 0x10000
I (697) boot: Disabling RNG early entropy source...
I (709) quad_psram: This chip is ESP32-D0WD
I (709) esp_psram: Found 8MB PSRAM device
I (709) esp_psram: Speed: 40MHz
I (713) esp_psram: PSRAM initialized, cache is in low/high (2-core) mode.
W (720) esp_psram: Virtual address not enough for PSRAM, map as much as we can. 4MB is mapped
I (729) cpu_start: Multicore app
I (1611) esp_psram: SPI SRAM memory test OK
I (1619) cpu_start: Pro cpu start user code
I (1619) cpu_start: cpu freq: 160000000 Hz
I (1619) app_init: Application information:
I (1622) app_init: Project name:     muse-luxe
I (1628) app_init: App version:      2025.6.2
I (1633) app_init: Compile time:     Jul  3 2025 11:20:04
I (1639) app_init: ELF file SHA256:  63293c1ce...
I (1644) app_init: ESP-IDF:          5.3.2
I (1649) efuse_init: Min chip rev:     v0.0
I (1654) efuse_init: Max chip rev:     v3.99 
I (1659) efuse_init: Chip rev:         v1.0
I (1664) heap_init: Initializing. RAM available for dynamic allocation:
I (1671) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (1677) heap_init: At 3FFB93F0 len 00026C10 (155 KiB): DRAM
I (1683) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (1690) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (1696) heap_init: At 4009B10C len 00004EF4 (19 KiB): IRAM
I (1703) esp_psram: Adding pool of 4096K of PSRAM memory to heap allocator
I (1712) spi_flash: detected chip: gd
I (1714) spi_flash: flash io: dio
E (1718) spi_flash: Detected size(4096k) smaller than the size in the binary image header(8192k). Probe failed.

assert failed: __esp_system_init_fn_init_flash startup_funcs.c:95 (flash_ret == ESP_OK)


Backtrace: 0x400846b9:0x3ffe3a80 0x4008da3d:0x3ffe3aa0 0x40094de5:0x3ffe3ac0 0x4013b84f:0x3ffe3be0 0x4013d21a:0x3ffe3c00 0x4013d252:0x3ffe3c20 0x40083d65:0x3ffe3c50 0x4007966a:0x3ffe3c90 |<-CORRUPTED




ELF file SHA256: 63293c1ce
```

**Comment by blackax1** [comment]
I was able to get the luxe_microWW.yaml to compile and install on the latest version of esphome (2025-8) Make sure you clean the build files before you install. It is still not perfect but its at least able to play audio streams from MA (music assistant) without dieing after 10 sec. Wake work is still hit and miss and responses are SLOW. I have not debuged enough to know if the ESP or a HA issue
